### ISSUE TITLE
Still fail to deploy

### ISSUE THREAD

**Issue by tina-hello** [tina-hello/serverless-dns#1]
@ignoramous I still can't deploy this project, but I can deploy the fork from https://github.com/serverless-dns/serverless-dns correctly

Failed deployment for celzero fork : https://github.com/tina-hello/serverless-dns/runs/3127808064?check_suite_focus=true#step:10:7

Successful deployment for serverless-dns fork : https://github.com/tina-hello/serverless-dns-1/runs/3127871438?check_suite_focus=true

**Comment by ignoramous** [comment]
Thanks. The repo at `celzero/serverless-dns` has been moved to `serverless-dns/serverless-dns`. While the code has diverged, the functionality remains the same.
